use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct InputSection {
    #[serde(rename = "RawInputMouseKeyboard")]
    pub raw_input_mouse_keyboard: Option<u8>,
    #[serde(rename = "InvertAxisY")]
    pub invert_axis_y: Option<u8>,
    #[serde(rename = "InvertMouseAxisY")]
    pub invert_mouse_axis_y: Option<u8>,
    #[serde(rename = "Rumble")]
    pub rumble: Option<u8>,
    #[serde(rename = "YawSensitivity")]
    pub yaw_sensitivity: Option<u32>,
    #[serde(rename = "PitchSensitivity")]
    pub pitch_sensitivity: Option<u32>,
    #[serde(rename = "DeadzoneLeftStick")]
    pub deadzone_left_stick: Option<u32>,
    #[serde(rename = "DeadzoneRightStick")]
    pub deadzone_right_stick: Option<u32>,
    #[serde(rename = "DeadzoneTriggerLeft")]
    pub deadzone_trigger_left: Option<u32>,
    #[serde(rename = "DeadzoneTriggerRight")]
    pub deadzone_trigger_right: Option<u32>,
    #[serde(rename = "DeadzoneSwitchInputStick")]
    pub deadzone_switch_input_stick: Option<u32>,
    #[serde(rename = "ControllerStickRotationCurve")]
    pub controller_stick_rotation_curve: Option<u32>,
    #[serde(rename = "MouseSensitivity")]
    pub mouse_sensitivity: Option<u32>,
    #[serde(rename = "MouseYawSensitivity")]
    pub mouse_yaw_sensitivity: Option<u32>,
    #[serde(rename = "MousePitchSensitivity")]
    pub mouse_pitch_sensitivity: Option<u32>,
    #[serde(rename = "MouseSensitivityMultiplierUnit")]
    pub mouse_sensitivity_multiplier_unit: Option<f64>,
    #[serde(rename = "MouseScroll")]
    pub mouse_scroll: Option<u8>,
    #[serde(rename = "XFactorAiming")]
    pub x_factor_aiming: Option<f64>,
    #[serde(rename = "ToggleAim")]
    pub toggle_aim: Option<u8>,
    #[serde(rename = "ToggleAimGamepad")]
    pub toggle_aim_gamepad: Option<u8>,
    #[serde(rename = "ToggleLean")]
    pub toggle_lean: Option<u8>,
    #[serde(rename = "ToggleSprint")]
    pub toggle_sprint: Option<u8>,
    #[serde(rename = "ToggleCrouch")]
    pub toggle_crouch: Option<u8>,
    #[serde(rename = "ToggleProne")]
    pub toggle_prone: Option<u8>,
    #[serde(rename = "ToggleWalk")]
    pub toggle_walk: Option<u8>,
    #[serde(rename = "ToggleDroneBoost")]
    pub toggle_drone_boost: Option<u8>,
    #[serde(rename = "ToggleGadgetDeploymentGamepad")]
    pub toggle_gadget_deployment_gamepad: Option<u8>,
    #[serde(rename = "ToggleGadgetDeploymentKeyboard")]
    pub toggle_gadget_deployment_keyboard: Option<u8>,
    #[serde(rename = "AimDownSights")]
    pub aim_down_sights: Option<u32>,
    #[serde(rename = "ADSGamepadUseSpecific")]
    pub ads_gamepad_use_specific: Option<u8>,
    #[serde(rename = "ADSGamepadSensitivityGlobal")]
    pub ads_gamepad_sensitivity_global: Option<u32>,
    #[serde(rename = "ADSGamepadSensitivity1x")]
    pub ads_gamepad_sensitivity_1x: Option<u32>,
    #[serde(rename = "ADSGamepadSensitivity1xHalf")]
    pub ads_gamepad_sensitivity_1x_half: Option<u32>,
    #[serde(rename = "ADSGamepadSensitivity2x")]
    pub ads_gamepad_sensitivity_2x: Option<u32>,
    #[serde(rename = "ADSGamepadSensitivity2xHalf")]
    pub ads_gamepad_sensitivity_2x_half: Option<u32>,
    #[serde(rename = "ADSGamepadSensitivity3x")]
    pub ads_gamepad_sensitivity_3x: Option<u32>,
    #[serde(rename = "ADSGamepadSensitivity4x")]
    pub ads_gamepad_sensitivity_4x: Option<u32>,
    #[serde(rename = "ADSGamepadSensitivity5x")]
    pub ads_gamepad_sensitivity_5x: Option<u32>,
    #[serde(rename = "ADSGamepadSensitivity12x")]
    pub ads_gamepad_sensitivity_12x: Option<u32>,
    #[serde(rename = "ADSGamepadMultiplierUnit")]
    pub ads_gamepad_multiplier_unit: Option<f64>,
    #[serde(rename = "AdvancedGamepadOptions")]
    pub advanced_gamepad_options: Option<u8>,
    #[serde(rename = "GamepadHorizontalFullTiltBoostModifier")]
    pub gamepad_horizontal_full_tilt_boost_modifier: Option<u32>,
    #[serde(rename = "GamepadVerticalFullTiltBoostModifier")]
    pub gamepad_vertical_full_tilt_boost_modifier: Option<u32>,
    #[serde(rename = "FullTiltBoostRampupDelay")]
    pub full_tilt_boost_rampup_delay: Option<f64>,
    #[serde(rename = "GamepadFullTiltBoostRampupTime")]
    pub gamepad_full_tilt_boost_rampup_time: Option<f64>,
    #[serde(rename = "ADSGamepadHorizontalFullTiltBoostModifier")]
    pub ads_gamepad_horizontal_full_tilt_boost_modifier: Option<u32>,
    #[serde(rename = "ADSGamepadVerticalFullTiltBoostModifier")]
    pub ads_gamepad_vertical_full_tilt_boost_modifier: Option<u32>,
    #[serde(rename = "ADSFullTiltBoostRampupDelay")]
    pub ads_full_tilt_boost_rampup_delay: Option<f64>,
    #[serde(rename = "ADSGamepadFullTiltBoostRampupTime")]
    pub ads_gamepad_full_tilt_boost_rampup_time: Option<f64>,
    #[serde(rename = "OuterDeadzoneRightStick")]
    pub outer_deadzone_right_stick: Option<u32>,
    #[serde(rename = "GamepadLookDampeningTime")]
    pub gamepad_look_dampening_time: Option<f64>,
    #[serde(rename = "AimDownSightsMouse")]
    pub aim_down_sights_mouse: Option<u32>,
    #[serde(rename = "ADSMouseUseSpecific")]
    pub ads_mouse_use_specific: Option<u8>,
    #[serde(rename = "ADSMouseSensitivityGlobal")]
    pub ads_mouse_sensitivity_global: Option<u32>,
    #[serde(rename = "ADSMouseSensitivity1x")]
    pub ads_mouse_sensitivity_1x: Option<u32>,
    #[serde(rename = "ADSMouseSensitivity1xHalf")]
    pub ads_mouse_sensitivity_1x_half: Option<u32>,
    #[serde(rename = "ADSMouseSensitivity2x")]
    pub ads_mouse_sensitivity_2x: Option<u32>,
    #[serde(rename = "ADSMouseSensitivity2xHalf")]
    pub ads_mouse_sensitivity_2x_half: Option<u32>,
    #[serde(rename = "ADSMouseSensitivity3x")]
    pub ads_mouse_sensitivity_3x: Option<u32>,
    #[serde(rename = "ADSMouseSensitivity4x")]
    pub ads_mouse_sensitivity_4x: Option<u32>,
    #[serde(rename = "ADSMouseSensitivity5x")]
    pub ads_mouse_sensitivity_5x: Option<u32>,
    #[serde(rename = "ADSMouseSensitivity12x")]
    pub ads_mouse_sensitivity_12x: Option<u32>,
    #[serde(rename = "ADSMouseMultiplierUnit")]
    pub ads_mouse_multiplier_unit: Option<f64>,
    #[serde(rename = "ControlSchemeIndex")]
    pub control_scheme_index: Option<u32>,
    #[serde(rename = "ControllerInputDevice")]
    pub controller_input_device: Option<u32>,
}
